#!/bin/bash

git fetch

query=$1
ticketName=${query#"https://1024pix.atlassian.net/browse/"}
ticketNumber=${ticketName#"PIX-"}

branchName=$(git branch -r | grep $ticketNumber)

if [[ "$branchName" =~ ^"*" ]]
then
  echo "Déjà sur la branche du ticket PIX-$ticketNumber"
  exit 0;
fi

if [ -z "$branchName" ]
then
  echo "Pas de branche trouvée pour le ticket PIX-$ticketNumber";
  exit 0;
fi

branchNameWithoutRemote=${branchName#"  origin/"}
git switch $branchNameWithoutRemote
