#!/bin/bash

git fetch

ticketNumber=$1
branchName=$(git branch -r | grep $ticketNumber)

if [[ "$branchName" =~ ^"*" ]]
then
  echo "Déjà sur la branche pour PIX-$ticketNumber"
  exit 0;
fi

if [ -z "$branchName" ]
then
  echo "Pas de branche locale pour PIX-$ticketNumber";
  exit 0;
fi

branchNameWithoutRemote=${branchName#"  origin/"}
git switch $branchNameWithoutRemote
